
def set_arguments(parser):
    parser.add_argument("--batch_size", type=int, default=256)
    parser.add_argument("--use_crf", type=bool, default=False)
    parser.add_argument("--hidden_dim", type=int, default=128)
    parser.add_argument("--num_layers", type=int, default=3)
    parser.add_argument("--bidirectional", type=bool, default=True)
    parser.add_argument("--embedding_dim", type=int, default=300)
    parser.add_argument("--tag_dim", type=int, default=2)
    parser.add_argument("--learning_rate", type=float, default=1e-3)
    parser.add_argument("--lr_decay_freq", type=int, default=5000)
    parser.add_argument("--lr_start_decay", type=int, default=5)
    parser.add_argument("--total_epoches", type=int, default=10)
    parser.add_argument("--max_clip_norm", type=int, default=5)
    parser.add_argument("--valid_freq", type=int, default=1000)
    parser.add_argument("--use_gpu", type=bool, default=True)
    parser.add_argument("--load_checkpoint", type=bool, default=False)
    parser.add_argument("--chpt_name", type=str, default="checkpoint.pt")
    parser.add_argument("--start_tag", type=str, default="<start>")
    parser.add_argument("--stop_tag", type=str, default="<stop>")
